### ISSUE TITLE
Cannot find module 'lodash' when using PNPM

### ISSUE THREAD

**Issue by biro456** [gajus/eslint-plugin-canonical#3]
Hey, I was checking out the `eslint-config-canonical` package and came across this.

`lodash` is being imported at runtime by `rules/filenameMatchExported.js`, but it's not listed in `dependencies`.

This turn into a problem when using [PNPM](https://pnpm.io) as package manager for the project, because the `node_modules` layout it creates doesn't let `eslint-plugin-canonical` have access to `lodash`.

```shell
Oops! Something went wrong! :(

ESLint: 8.6.0

Error: Failed to load plugin 'canonical' declared in '.eslintrc.yaml » eslint-config-canonical': Cannot find module 'lodash'
Require stack:
- /project/node_modules/.pnpm/eslint-plugin-canonical@2.4.2_eslint@8.6.0/node_modules/eslint-plugin-canonical/dist/rules/filenameMatchExported.js
- /project/node_modules/.pnpm/eslint-plugin-canonical@2.4.2_eslint@8.6.0/node_modules/eslint-plugin-canonical/dist/index.js
- /project/node_modules/.pnpm/@eslint+eslintrc@1.0.5/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/project/node_modules/.pnpm/v8-compile-cache@2.3.0/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/project/node_modules/.pnpm/eslint-plugin-canonical@2.4.2_eslint@8.6.0/node_modules/eslint-plugin-canonical/dist/rules/filenameMatchExported.js:10:15)
    at Module._compile (/project/node_modules/.pnpm/v8-compile-cache@2.3.0/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

**Comment by gajus** [comment]
Thank you
